# Generated by Django 4.1.3 on 2022-12-12 16:30

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Nombre de susuario"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "primer_apellido",
                    models.CharField(max_length=30, verbose_name="Primer apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(max_length=30, verbose_name="Segundo apellido"),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("H", "Hombre"), ("M", "Mujer"), ("HO", "Otros")],
                        max_length=6,
                        verbose_name="Genero",
                    ),
                ),
                ("fecha_nac", models.DateField(verbose_name="Fecha de nacimiento")),
                ("huespedes", models.IntegerField(verbose_name="Huespedes")),
                (
                    "telefono",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{8,15}$"
                            )
                        ],
                        verbose_name="Telephone",
                    ),
                ),
                (
                    "hora_llegada",
                    models.DateTimeField(verbose_name="Hora estimada de llegada"),
                ),
                (
                    "comentarios",
                    ckeditor.fields.RichTextField(
                        blank=True, default="", null=True, verbose_name="Comentarios"
                    ),
                ),
                ("key_room", models.IntegerField(verbose_name="Select a Key Room")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
