# Generated by Django 4.1.3 on 2022-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="comentarios",),
        migrations.RemoveField(model_name="user", name="hora_llegada",),
        migrations.RemoveField(model_name="user", name="huespedes",),
        migrations.RemoveField(model_name="user", name="key_room",),
        migrations.AlterField(
            model_name="user",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("H", "Hombre"), ("M", "Mujer"), ("O", "Otros")],
                max_length=6,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="segundo_apellido",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Segundo apellido"
            ),
        ),
    ]
